// passgen-react/src/components/Form.js
import React, {useState} from 'react';
import Checkbox from "./Checkbox";
import Radio from "./Radio";
import {init_checkboxes, passwords_count, radios} from "../app-config";


export default function Form(props) {
    const {setPasswords} = props;
    const [length, setLength] = useState(12);
    const [checkboxes, setCheckboxes] = useState(init_checkboxes);

    function handleFormChange() {
        const form = document.querySelector('#form');
        setLength(Number(form['pass_length'].value));
        setCheckboxes(
            checkboxes.map(checkbox => {
                checkbox.checked = form[checkbox.name].checked;
                return checkbox
            })
        );
        !generateString()
            ?form.querySelector('button').classList.add('disabled')
            :form.querySelector('button').classList.remove('disabled')
    }

    function generateString(){
        return checkboxes.map(
            checkbox => checkbox.checked ? checkbox.string : ''
        ).join('');
    }

    function handleFormSubmit(e) {
        e.preventDefault();
        const string = generateString();
        const passwords = Array(passwords_count).fill('').map(
            () => generatePassword(string, length)
        );
        setPasswords(passwords)
    }

    return (
        <form onChange={handleFormChange} onSubmit={handleFormSubmit} id="form">
            <div className="form-body">
                <div>
                    {checkboxes.map(o => <Checkbox key={o.name} checkbox={o}/>)}
                </div>
                <div>
                    {radios.map(o => <Radio key={o.value} radio={o}/>)}
                </div>
            </div>
            <div className="form-footer">
                <button className="btn">Generate!</button>
            </div>
        </form>
    );
}

function generatePassword(string, length) {
    let password = '';
    for (let i = 0; i < length; i++) {
        const position = Math.floor(Math.random() * string.length);
        password += string[position]
    }
    return password
}

// passgen-svelte/src/components/Form.svelte
<script>
    import Checkbox from './Checkbox.svelte'
    import Radio from './Radio.svelte'
    import {checkboxes, count, radios} from "../form-config"

    export let setPasswords
    let string
    let length

    const handleFormSubmit = e => {
        e.preventDefault()
        handleFormChange()
        setPasswords(
            new Array(count)
                .fill('')
                .map(() => generatePassword(string, length))
        )
    }

    const handleFormChange = () => {
        const form = document.querySelector('#form')
        length = form['pass-length'].value
        string = checkboxes.map(ch => {
            return ch.checked ? ch.string : null
        }).join('')
        !string
            ? form.querySelector('button').disabled = true
            : form.querySelector('button').disabled = false
    }

    function generatePassword(string, length) {
        let password = '';
        for (let i = 0; i < length; i++) {
            const position = Math.floor(Math.random() * string.length);
            password += string[position]
        }
        return password
    }

</script>

<form id="form" on:change={handleFormChange} on:submit={handleFormSubmit}>
    <div class="flex">
        <div>
            {#each checkboxes as checkbox}
                <Checkbox checkbox={checkbox}/>
            {/each}
        </div>
        <div>
            {#each radios as radio}
                <Radio radio={radio}/>
            {/each}
        </div>
    </div>
    <button>Generate!</button>
</form>

<style>
    div.flex {
        display: flex;
        justify-content: center;
        gap: 3em;
        text-align: left;
    }
</style>
